services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    ports:
      - "9042:9042"
      - "9180:9180"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "10000:10000"
    volumes:
      - scylla_data:/var/lib/scylla
    environment:
      - SCYLLA_CPUS=2
      - SCYLLA_MEM=2G

volumes:
  scylla_data:
